// Auto-generated by scripts/generate-certificates.cjs
export const certificates = [
  {
    "group": "Andela Kubernetes  Certificates",
    "items": [
      {
        "id": 2001,
        "title": "john brown ouma GitOps certificate",
        "file": "certificates/Andela Kubernetes  Certificates/john-brown-ouma-GitOps-certificate.pdf",
        "url": "/certificates/Andela%20Kubernetes%20%20Certificates/john-brown-ouma-GitOps-certificate.pdf"
      },
      {
        "id": 2002,
        "title": "john brown ouma Kubernetes and Cloud Native Essentialscertificate",
        "file": "certificates/Andela Kubernetes  Certificates/john-brown-ouma-Kubernetes-and-Cloud-Native-Essentialscertificate.pdf",
        "url": "/certificates/Andela%20Kubernetes%20%20Certificates/john-brown-ouma-Kubernetes-and-Cloud-Native-Essentialscertificate.pdf"
      }
    ]
  },
  {
    "group": "campus_ambassador_devtown.pdf",
    "items": [
      {
        "id": 2003,
        "title": "campus ambassador devtown",
        "file": "certificates/campus_ambassador_devtown.pdf",
        "url": "/certificates/campus_ambassador_devtown.pdf"
      }
    ]
  },
  {
    "group": "Cyber Shujaa Data & AI Certificate .pdf",
    "items": [
      {
        "id": 2004,
        "title": "Cyber Shujaa Data & AI Certificate",
        "file": "certificates/Cyber Shujaa Data & AI Certificate .pdf",
        "url": "/certificates/Cyber%20Shujaa%20Data%20&%20AI%20Certificate%20.pdf"
      }
    ]
  },
  {
    "group": "cybersecurity_xaltius.pdf",
    "items": [
      {
        "id": 2005,
        "title": "cybersecurity xaltius",
        "file": "certificates/cybersecurity_xaltius.pdf",
        "url": "/certificates/cybersecurity_xaltius.pdf"
      }
    ]
  },
  {
    "group": "data_science_xaltius.pdf",
    "items": [
      {
        "id": 2006,
        "title": "data science xaltius",
        "file": "certificates/data_science_xaltius.pdf",
        "url": "/certificates/data_science_xaltius.pdf"
      }
    ]
  },
  {
    "group": "digital_marketing_xaltius.pdf",
    "items": [
      {
        "id": 2007,
        "title": "digital marketing xaltius",
        "file": "certificates/digital_marketing_xaltius.pdf",
        "url": "/certificates/digital_marketing_xaltius.pdf"
      }
    ]
  },
  {
    "group": "Google Cybersecurity Certificate",
    "items": [
      {
        "id": 2008,
        "title": "Coursera AG4148ZKIV0H",
        "file": "certificates/Google Cybersecurity Certificate/Coursera AG4148ZKIV0H.pdf",
        "url": "/certificates/Google%20Cybersecurity%20Certificate/Coursera%20AG4148ZKIV0H.pdf"
      },
      {
        "id": 2009,
        "title": "Coursera F02AJJHFN8ZM",
        "file": "certificates/Google Cybersecurity Certificate/Coursera F02AJJHFN8ZM.pdf",
        "url": "/certificates/Google%20Cybersecurity%20Certificate/Coursera%20F02AJJHFN8ZM.pdf"
      },
      {
        "id": 2010,
        "title": "Coursera GJPJSVEGE98A",
        "file": "certificates/Google Cybersecurity Certificate/Coursera GJPJSVEGE98A.pdf",
        "url": "/certificates/Google%20Cybersecurity%20Certificate/Coursera%20GJPJSVEGE98A.pdf"
      },
      {
        "id": 2011,
        "title": "Coursera H2OC3K5DT1FU",
        "file": "certificates/Google Cybersecurity Certificate/Coursera H2OC3K5DT1FU.pdf",
        "url": "/certificates/Google%20Cybersecurity%20Certificate/Coursera%20H2OC3K5DT1FU.pdf"
      },
      {
        "id": 2012,
        "title": "Coursera H4II3COCVZE7",
        "file": "certificates/Google Cybersecurity Certificate/Coursera H4II3COCVZE7.pdf",
        "url": "/certificates/Google%20Cybersecurity%20Certificate/Coursera%20H4II3COCVZE7.pdf"
      },
      {
        "id": 2013,
        "title": "Coursera J3UOOI06HAY0",
        "file": "certificates/Google Cybersecurity Certificate/Coursera J3UOOI06HAY0.pdf",
        "url": "/certificates/Google%20Cybersecurity%20Certificate/Coursera%20J3UOOI06HAY0.pdf"
      },
      {
        "id": 2014,
        "title": "Coursera QZOA4746A21L",
        "file": "certificates/Google Cybersecurity Certificate/Coursera QZOA4746A21L.pdf",
        "url": "/certificates/Google%20Cybersecurity%20Certificate/Coursera%20QZOA4746A21L.pdf"
      },
      {
        "id": 2015,
        "title": "Coursera VW4JRZA7GB8V",
        "file": "certificates/Google Cybersecurity Certificate/Coursera VW4JRZA7GB8V.pdf",
        "url": "/certificates/Google%20Cybersecurity%20Certificate/Coursera%20VW4JRZA7GB8V.pdf"
      },
      {
        "id": 2016,
        "title": "Coursera WLSSW33UADPC",
        "file": "certificates/Google Cybersecurity Certificate/Coursera WLSSW33UADPC.pdf",
        "url": "/certificates/Google%20Cybersecurity%20Certificate/Coursera%20WLSSW33UADPC.pdf"
      }
    ]
  },
  {
    "group": "hotstar_clone_devtown_aws.pdf",
    "items": [
      {
        "id": 2017,
        "title": "hotstar clone devtown aws",
        "file": "certificates/hotstar_clone_devtown_aws.pdf",
        "url": "/certificates/hotstar_clone_devtown_aws.pdf"
      }
    ]
  },
  {
    "group": "hotstar_clone_gdsc.pdf",
    "items": [
      {
        "id": 2018,
        "title": "hotstar clone gdsc",
        "file": "certificates/hotstar_clone_gdsc.pdf",
        "url": "/certificates/hotstar_clone_gdsc.pdf"
      }
    ]
  },
  {
    "group": "python_ai_aws.pdf",
    "items": [
      {
        "id": 2019,
        "title": "python ai aws",
        "file": "certificates/python_ai_aws.pdf",
        "url": "/certificates/python_ai_aws.pdf"
      }
    ]
  },
  {
    "group": "python_ai_gdsc.pdf",
    "items": [
      {
        "id": 2020,
        "title": "python ai gdsc",
        "file": "certificates/python_ai_gdsc.pdf",
        "url": "/certificates/python_ai_gdsc.pdf"
      }
    ]
  },
  {
    "group": "python_ai_microsoft.pdf",
    "items": [
      {
        "id": 2021,
        "title": "python ai microsoft",
        "file": "certificates/python_ai_microsoft.pdf",
        "url": "/certificates/python_ai_microsoft.pdf"
      }
    ]
  }
] as const;
export type CertGroup = (typeof certificates)[number];
