// This file is auto-generated by scripts/generate-docs.cjs
export const documents = [
  {
    "id": 1001,
    "title": "Generative AI and RAG",
    "excerpt": "Generative AI and RAG",
    "category": "Data Science",
    "date": "2024-01-01",
    "readTime": "PDF",
    "tags": [],
    "link": "/CyberShujaa%20documents/Generative%20AI%20and%20RAG.pdf",
    "featured": false
  },
  {
    "id": 1002,
    "title": "Geoffrey Hintons Interview on AI",
    "excerpt": "Geoffrey Hintons Interview on AI",
    "category": "Data Science",
    "date": "2024-01-01",
    "readTime": "PDF",
    "tags": [],
    "link": "/CyberShujaa%20documents/Geoffrey%20Hintons%20Interview%20on%20AI.pdf",
    "featured": false
  },
  {
    "id": 1003,
    "title": "HR Dashboard analysis Tableau",
    "excerpt": "HR Dashboard analysis Tableau",
    "category": "Data Science",
    "date": "2024-01-01",
    "readTime": "PDF",
    "tags": [],
    "link": "/CyberShujaa%20documents/HR%20Dashboard%20analysis-%20Tableau.pdf",
    "featured": false
  },
  {
    "id": 1004,
    "title": "Web Scrapping Week One Report",
    "excerpt": "Web Scrapping Week One Report",
    "category": "Data Science",
    "date": "2024-01-01",
    "readTime": "PDF",
    "tags": [],
    "link": "/CyberShujaa%20documents/John%20Brown%20Ouma%20Web%20Scrapping%20Week%20One%20Report.pdf",
    "featured": false
  },
  {
    "id": 1005,
    "title": "Data Wrangling project",
    "excerpt": "Data Wrangling project",
    "category": "Data Science",
    "date": "2024-01-01",
    "readTime": "PDF",
    "tags": [],
    "link": "/CyberShujaa%20documents/John-Brown-Ouma-Data-Wrangling-project.pdf",
    "featured": false
  },
  {
    "id": 1006,
    "title": "Business Intelligence Power BI",
    "excerpt": "Business Intelligence Power BI",
    "category": "Data Science",
    "date": "2024-01-01",
    "readTime": "PDF",
    "tags": [],
    "link": "/CyberShujaa%20documents/John_Brown_Ouma_Business_Intelligence_Power_BI.pdf",
    "featured": false
  },
  {
    "id": 1007,
    "title": "Titanic EDA",
    "excerpt": "John Brown Ouma Titanic EDA",
    "category": "Data Science",
    "date": "2024-01-01",
    "readTime": "PDF",
    "tags": [],
    "link": "/CyberShujaa%20documents/John_Brown_Ouma_Titanic_EDA.pdf",
    "featured": false
  },
  {
    "id": 1008,
    "title": "Linear regression model",
    "excerpt": "Linear regression model",
    "category": "Data Science",
    "date": "2024-01-01",
    "readTime": "PDF",
    "tags": [],
    "link": "/CyberShujaa%20documents/Linear_regression_model.pdf",
    "featured": false
  },
  {
    "id": 1009,
    "title": "MLOPs California Housing Price Prediction",
    "excerpt": "MLOPs California Housing Price Prediction",
    "category": "Data Science",
    "date": "2024-01-01",
    "readTime": "PDF",
    "tags": [],
    "link": "/CyberShujaa%20documents/MLOPs%20-%20California%20Housing%20Price%20Prediction.pdf",
    "featured": false
  },
  {
    "id": 1010,
    "title": "MNIST handwritten digit classification",
    "excerpt": "MNIST handwritten digit classification",
    "category": "Data Science",
    "date": "2024-01-01",
    "readTime": "PDF",
    "tags": [],
    "link": "/CyberShujaa%20documents/MNIST%20handwritten%20digit%20classification.pdf",
    "featured": false
  },
  {
    "id": 1011,
    "title": "Natural Language Processing With Transformers",
    "excerpt": "Natural Language Processing With Transformers",
    "category": "Data Science",
    "date": "2024-01-01",
    "readTime": "PDF",
    "tags": [],
    "link": "/CyberShujaa%20documents/Natural%20Language%20Processing%20With%20Transformers.pdf",
    "featured": false
  },
  {
    "id": 1012,
    "title": "Supervised machine learning Classification models",
    "excerpt": "Supervised machine learning Classification models",
    "category": "Data Science",
    "date": "2024-01-01",
    "readTime": "PDF",
    "tags": [],
    "link": "/CyberShujaa%20documents/Supervised%20machine%20learning%20Classification%20models.pdf",
    "featured": false
  }
] as const;

export type Doc = (typeof documents)[number];
