import fs from 'fs';
import path from 'path';

type Doc = {
  id: number;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  readTime: string;
  tags: string[];
  link: string;
  featured?: boolean;
};

const PUBLIC_DIR = path.resolve(__dirname, '..', 'public');
const TARGET_FOLDER = path.join(PUBLIC_DIR, 'CyberShujaa documents');
const OUT_FILE = path.resolve(__dirname, '..', 'src', 'lib', 'documents.ts');

function slugToTitle(filename: string) {
  const name = filename.replace(/\.pdf$/i, '');
  return name.replace(/[_-]+/g, ' ').replace(/\s+/g, ' ').trim();
}

function main() {
  if (!fs.existsSync(TARGET_FOLDER)) {
    console.error('Target folder not found:', TARGET_FOLDER);
    process.exit(1);
  }

  const files = fs.readdirSync(TARGET_FOLDER).filter(f => f.toLowerCase().endsWith('.pdf'));

  const docs: Doc[] = files.map((f, idx) => {
    const title = slugToTitle(f);
    return {
      id: 1000 + idx + 1,
      title,
      excerpt: title,
      category: 'Data Science',
      date: '2024-01-01',
      readTime: 'PDF',
      tags: [],
      link: encodeURI(`/CyberShujaa documents/${f}`),
      featured: false,
    };
  });

  const content = `// This file is auto-generated by scripts/generate-docs.ts
export const documents = ${JSON.stringify(docs, null, 2)} as const;
`;

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, content, 'utf8');
  console.log('Wrote', OUT_FILE);
}

main();
